name: flight-task
version: 0.1.0
synopsis: Tasks to fly.
description: Tasks for hang gliding and paragliding competitons.
category: Flight
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/task
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
dependencies:
- base >=4.9.1.0 && <5
- numbers
- fgl
- uom-plugin
- bifunctors
- aeson
- scientific
- mtl
- detour-via-sci
- siggy-chardust
- flight-units
- flight-latlng
- flight-zone
- flight-earth
library:
  exposed-modules: Flight.Task
  source-dirs: library
tests:
  task:
    main: Task.hs
    source-dirs:
    - library
    - test-suite-task
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - tasty-compare
    - smallcheck

