# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - numbers
  - fgl
  - uom-plugin
  - bifunctors
  - aeson
  - scientific
  - mtl
  - hcoord
  - aeson-rational
  - siggy-chardust
  - flight-units
  - flight-latlng
  - flight-zone
  source-dirs: library
  exposed-modules:
  - Flight.TaskTrack
  - Flight.TaskTrack.Double
  - Flight.TaskTrack.Rational
  - Flight.Task
  - Flight.Cylinder.Double
  - Flight.Cylinder.Rational
  - Flight.PointToPoint.Double
  - Flight.PointToPoint.Rational
  - Flight.Projected.Double
  - Flight.Projected.Rational
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-task
synopsis: Tasks to fly.
description: Tasks for hang gliding and paragliding competitons.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-task
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - numbers
    - fgl
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - mtl
    - hcoord
    - aeson-rational
    - siggy-chardust
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  task:
    dependencies:
    - base
    - numbers
    - fgl
    - bifunctors
    - uom-plugin
    - aeson
    - scientific
    - mtl
    - hcoord
    - siggy-chardust
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Task.hs
    source-dirs:
    - library
    - test-suite-task
version: '0.1.0'
