flags: {}
packages:
- '.'
- location: ../siggy-chardust
  extra-dep: true
- location: ../units
  extra-dep: true
- location: ../latlng
  extra-dep: true
- location: ../zone
  extra-dep: true
- location: ../tasty-compare
  extra-dep: true
- location:
    git: https://github.com/danfran/hcoord.git
    commit: e308934570874a6ce7f7ebdbf51a3c34e4acd745
  extra-dep: true
- location:
    git: https://github.com/haskell/fgl.git
    commit: e29503775e474b7a7cd8951b6bebcf1529b888b5
  extra-dep: true
- location:
    git: https://github.com/adamgundry/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps: []
resolver: nightly-2017-11-23
local-bin-path: ../__shake-build
