# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  extract-task:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - bytestring
    - clock
    - formatting
    - flight-comp
    - flight-fsdb
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: prod-apps/extract-task
  task-length:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - formatting
    - flight-units
    - flight-comp
    - flight-task
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/task-length
  cross-zone:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - formatting
    - siggy-chardust
    - flight-units
    - flight-comp
    - flight-latlng
    - flight-kml
    - flight-track
    - flight-zone
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/cross-zone
  tag-zone:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - time
    - formatting
    - siggy-chardust
    - flight-units
    - flight-comp
    - flight-kml
    - flight-track
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/tag-zone
  align-time:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - time
    - formatting
    - cassava
    - vector
    - split
    - siggy-chardust
    - flight-units
    - flight-latlng
    - flight-comp
    - flight-kml
    - flight-track
    - flight-zone
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/align-time
  discard-further:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - time
    - formatting
    - cassava
    - vector
    - split
    - siggy-chardust
    - flight-units
    - flight-latlng
    - flight-comp
    - flight-kml
    - flight-track
    - flight-zone
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/discard-further
  mask-track:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - clock
    - formatting
    - numbers
    - siggy-chardust
    - flight-units
    - flight-latlng
    - flight-comp
    - flight-kml
    - flight-track
    - flight-zone
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: prod-apps/mask-track
  test-fsdb-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-comp
    - flight-fsdb
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/fsdb-parser
  test-igc-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-igc
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/igc-parser
  test-kml-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-kml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/kml-parser
extra-source-files:
- package.yaml
- changelog.md
- readme.md
- stack.yaml
ghc-options: -Wall
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flare-timing 
synopsis: A collection of apps and libraries for scoring hang gliding and paragliding competitions.
description: Scoring and viewing hang gliding and paragliding competitions.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - test-suite-hlint
version: '0.1.0'
