# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  comp-serve:
    dependencies:
    - base
    - servant
    - servant-server
    - transformers
    - aeson
    - wai
    - wai-cors
    - warp
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - bytestring
    - flight-comp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: yaml/app-serve
  comp-xml-to-yaml:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - bytestring
    - flight-comp
    - flight-fsdb
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: yaml/comp-xml-to-yaml
  mask-tracks:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - uom-plugin
    - bytestring
    - siggy-chardust
    - flight-units
    - flight-comp
    - flight-kml
    - flight-track
    - flight-task
    - flight-gap
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Main.hs
    source-dirs: yaml/mask
  fsdb-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-comp
    - flight-fsdb
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/fsdb-parser
  igc-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-igc
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/igc-parser
  kml-parser:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-kml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-apps/kml-parser
extra-source-files:
- package.yaml
- changelog.md
- readme.md
- stack.yaml
ghc-options: -Wall
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flare-timing 
synopsis: A collection of apps and libraries for scoring hang gliding and paragliding competitions.
description: Scoring and viewing hang gliding and paragliding competitions.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - test-suite-hlint
version: '0.1.0'
