# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - aeson
  - scientific
  - containers
  - unordered-containers
  - time
  - cassava
  - bytestring
  - directory
  - filepath
  - filemanip
  - lens
  - mtl
  - uom-plugin
  - aeson-via-sci
  - flight-latlng
  - flight-zone
  - flight-route
  - flight-gap
  - flight-comp
  - flight-kml
  - flight-mask
  source-dirs: library
  exposed-modules:
  - Flight.Lookup.Route
  - Flight.Lookup.Cross
  - Flight.Lookup.Tag
  - Flight.Lookup
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
name: flight-lookup
synopsis: Hang gliding and paragliding competition data access.
description: Lookup items for a task, for a pilot, etc.
category: Data
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - split
    - path
    - aeson
    - scientific
    - containers
    - unordered-containers
    - time
    - cassava
    - bytestring
    - directory
    - filepath
    - filemanip
    - lens
    - mtl
    - uom-plugin
    - aeson-via-sci
    - flight-latlng
    - flight-zone
    - flight-route
    - flight-gap
    - flight-comp
    - flight-kml
    - flight-mask
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
