flags: {}
packages:
- '.'
- location: ../aeson-via-sci
  extra-dep: true
- location: ../aeson-via-uom
  extra-dep: true
- location: ../siggy-chardust
  extra-dep: true
- location: ../units
  extra-dep: true
- location: ../earth
  extra-dep: true
- location: ../latlng
  extra-dep: true
- location: ../zone
  extra-dep: true
- location: ../route
  extra-dep: true
- location: ../gap
  extra-dep: true
- location: ../comp
  extra-dep: true
- location: ../kml
  extra-dep: true
- location: ../igc
  extra-dep: true
- location: ../mask
  extra-dep: true
- location: ../span
  extra-dep: true
- location: ../task
  extra-dep: true
- location: ../track
  extra-dep: true
- location: ../scribe
  extra-dep: true
- location:
    git: https://github.com/blockscope/hcoord.git
    commit: efee5918967a4b5309924bb6ac62c2daa56983a1
  subdirs:
  - hcoord
  - hcoord-utm
  extra-dep: true
- location:
    git: https://github.com/adamgundry/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps:
- hxt-xpath-9.1.2.2
resolver: nightly-2018-01-09
local-bin-path: ../__shake-build
