# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# To avoid running out of memory, add a swap file.
# SEE: https://www.reddit.com/r/haskell/comments/5ov5k1/how_to_stack_build_specifically_lens_on_a_low/
# - sudo mkdir -v /var/cache/swap
# - cd /var/cache/swap
# - sudo dd if=/dev/zero of=swapfile bs=1K count=4M
# - sudo chmod 600 swapfile
# - sudo mkswap swapfile
# - sudo swapon swapfile
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack build build-flare-timing --only-dependencies --install-ghc --no-terminal
- stack install dhall hpack-dhall --no-terminal
- stack test flare-timing --only-dependencies --no-terminal

script:
# Build the package, its tests, and its docs and run the tests
- stack build build-flare-timing --no-terminal
- ./stack-shake-build.sh cabal-files
- ./stack-shake-build.sh stack-test-apps
- ./stack-shake-build.sh stack-prod-apps
# NOTE: The stack-lint target is timing out on travis-ci.org
# The job exceeded the maximum time limit for jobs, and has been terminated.
# - ./stack-shake-build.sh stack-lint
# Let's try them as separate targets.
 - ./stack-shake-build.sh stack-lint-build
 - ./stack-shake-build.sh stack-lint-detour-via-sci
 - ./stack-shake-build.sh stack-lint-detour-via-uom
 - ./stack-shake-build.sh stack-lint-siggy-chardust
 - ./stack-shake-build.sh stack-lint-tasty-compare
 - ./stack-shake-build.sh stack-lint-flare-timing
 - ./stack-shake-build.sh stack-lint-cmd
 - ./stack-shake-build.sh stack-lint-comp
 - ./stack-shake-build.sh stack-lint-earth
 - ./stack-shake-build.sh stack-lint-fsdb
 - ./stack-shake-build.sh stack-lint-gap
 - ./stack-shake-build.sh stack-lint-igc
 - ./stack-shake-build.sh stack-lint-kml
 - ./stack-shake-build.sh stack-lint-latlng
 - ./stack-shake-build.sh stack-lint-lookup
 - ./stack-shake-build.sh stack-lint-mask
 - ./stack-shake-build.sh stack-lint-route
 - ./stack-shake-build.sh stack-lint-span
 - ./stack-shake-build.sh stack-lint-scribe
 - ./stack-shake-build.sh stack-lint-task
 - ./stack-shake-build.sh stack-lint-track
 - ./stack-shake-build.sh stack-lint-units
 - ./stack-shake-build.sh stack-lint-zone
# NOTE: Building the test suites is timing out on travis-ci.org
# The job exceeded the maximum time limit for jobs, and has been terminated.
# - ./stack-shake-build.sh stack-test-suites
