sudo: required
matrix:
  include:
  - env: GHCVER=8.2.2
  - os: osx

script:
- export HLINT_ARGUMENTS=src
- export UNIPLATE_VERBOSE=-1
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
