# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  flight-igc:
    dependencies:
    - base
    - time
    - shake
    - extra
    - ansi-terminal
    - directory
    - filepath
    - system-filepath
    - filemanip
    - template-haskell
    - raw-strings-qq
    - text
    - cmdargs
    - mtl
    - transformers
    - flight-igc 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
library:
  dependencies:
  - base
  - parsec
  source-dirs: library
  exposed-modules:
  - Data.Waypoint
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-igc 
synopsis: A parser for flight IGC files, a waypoint format from the International Gliding Commission of FAI.
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - flight-igc 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs: test-suite
version: '0.1.0'
