# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  flight-fsdb-serve:
    dependencies:
    - base
    - servant
    - servant-server
    - transformers
    - aeson
    - wai
    - wai-cors
    - warp
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-fsdb 
    - bytestring
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: fsdb/app-serve
  flight-yaml-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - aeson
    - flight-fsdb 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: yaml/app-cmd
  flight-fsdb-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-fsdb 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: fsdb/app-cmd
  flight-igc-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-igc 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: igc/app-cmd
  flight-kml-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-kml 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: kml/app-cmd
  flight-track-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-fsdb 
    - flight-kml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: track/app-cmd
  flare-timing-build-cmd:
    dependencies:
    - base
    - ansi-terminal
    - shake
    - time
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: build/app-cmd
extra-source-files:
- package.yaml
- changelog.md
- readme.md
- stack.yaml
ghc-options: -Wall
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flare-timing 
synopsis: A collection of apps and libraries for scoring hang gliding and paragliding competitions.
description: Scoring and viewing hang gliding and paragliding competitions.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - test-suite-hlint
version: '0.1.0'
