# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  flight-kml-cmd:
    dependencies:
    - base
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-kml 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - parsec
  - hxt
  - path
  - hxt-xpath
  source-dirs: library
  exposed-modules:
  - Data.Waypoint
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-kml 
synopsis: A parser for KML files.
description: KML can be a source of flight waypoints.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-kml
tests:
  hlint:
    dependencies:
    - base
    - parsec
    - hxt
    - path
    - hxt-xpath
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  parse:
    dependencies:
    - base
    - parsec
    - hxt
    - path
    - hxt-xpath
    - raw-strings-qq
    - split
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Parse.hs
    source-dirs:
    - library
    - test-suite-parse
version: '0.1.0'
