# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - parsec
  - hxt
  - path
  - hxt-xpath
  - aeson
  - scientific
  source-dirs: library
  exposed-modules:
  - Data.Flight.Types
  - Data.Flight.Waypoint
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-fsdb 
synopsis: A parser for fsdb, the database XML format of FS.
description: Hang gliding and paragliding competitors, tasks and results as XML.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-fsdb
tests:
  hlint:
    dependencies:
    - base
    - parsec
    - hxt
    - path
    - hxt-xpath
    - hlint
    - aeson
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  parse:
    dependencies:
    - base
    - parsec
    - hxt
    - path
    - hxt-xpath
    - raw-strings-qq
    - split
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Parse.hs
    source-dirs:
    - library
    - test-suite-parse
version: '0.1.0'
