# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options:
- -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - newtype
  - scientific
  - aeson
  - cassava
  - template-haskell
  source-dirs: library
  exposed-modules:
  - Data.Aeson.Via.Scientific
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: aeson-via-sci
synopsis: JSON encoding and decoding for rationals via scientific.
description: Lossy JSON encoding for rationals.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - newtype
    - scientific
    - aeson
    - cassava
    - template-haskell
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
