name: aeson-via-uom
version: '0.1.0'
synopsis: JSON encoding and decoding for rationals via scientific.
description: Lossy JSON encoding for rationals.
category: Flight
github: BlockScope/flare-timing
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
  
library:
  dependencies:
  - base >=4.5 && <5
  - newtype
  - scientific
  - aeson
  - uom-plugin
  - aeson-via-sci
  - flight-units
  source-dirs: library
  exposed-modules:
  - Data.Aeson.Via.UnitsOfMeasure

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - newtype
    - scientific
    - aeson
    - uom-plugin
    - aeson-via-sci
    - flight-units
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
