homepage: https://github.com/blockscope/flare-timing/tree/master/kml#readme
library:
  source-dirs: library
  exposed-modules:
  - Flight.Kml
  - Flight.Kml.Internal
tests:
  doctest:
    source-dirs:
    - library
    - test-suite-doctest
    main: DocTest.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - template-haskell
    - doctest
  parse:
    source-dirs:
    - library
    - test-suite-parse
    main: Parse.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - split
    - parsec
    - hxt
    - path
    - hxt-xpath
    - aeson
    - time
    - raw-strings-qq
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    - detour-via-sci
    - siggy-chardust
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
category: Data, Parsing, Geography, Gps, Flight, XML, KML
license-file: LICENSE.md
maintainer: phil.dejoux@blockscope.com
ghc-options:
- -Wall
dependencies:
- base >=4.9.1.0 && <5
- split
- parsec
- hxt
- path
- hxt-xpath
- aeson
- time
- detour-via-sci
- siggy-chardust
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
name: flight-kml
version: 1.0.1
extra-source-files:
- package.dhall
- changelog.md
- README.md
- ! '**/*.kml'
synopsis: Parsing of pilot tracklogs dumped as KML.
author: Phil de Joux
github: blockscope/flare-timing/kml
tested-with: GHC == 8.2.2
license: MPL-2.0
description: Provides parsing of dumped tracklogs. In hang gliding and paragliding
  competitions when FS and GpsDump are paired in competition mode a pilot's tracklog
  is dumped as KML. This is exlained in detail on the FS wiki.

