# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - numbers
  - fgl
  - uom-plugin
  - bifunctors
  - aeson
  - scientific
  - mtl
  - hcoord
  - aeson-via-sci
  - siggy-chardust
  - flight-units
  - flight-latlng
  - flight-zone
  source-dirs: library
  exposed-modules:
  - Flight.Sphere.Cylinder.Double
  - Flight.Sphere.Cylinder.Rational
  - Flight.Sphere.PointToPoint.Double
  - Flight.Sphere.PointToPoint.Rational
  - Flight.Sphere.Separated
  - Flight.Sphere
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-earth-sphere
synopsis: Distances on the FAI sphere.
description: Distances on the FAI sphere for hang gliding and paragliding competitons.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-task
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - numbers
    - fgl
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - mtl
    - hcoord
    - aeson-via-sci
    - siggy-chardust
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  sphere:
    dependencies:
    - base
    - hlint
    - numbers
    - fgl
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - mtl
    - hcoord
    - aeson-via-sci
    - siggy-chardust
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Sphere.hs
    source-dirs:
    - library
    - test-suite-sphere
version: '0.1.0'
