# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - aeson
  - scientific
  - containers
  - unordered-containers
  - time
  - cassava
  - bytestring
  - directory
  - filepath
  - filemanip
  - mtl
  - yaml
  - vector
  - aeson-via-sci
  - flight-latlng
  - flight-zone
  - flight-route
  - flight-gap
  - flight-comp
  source-dirs: library
  exposed-modules:
  - Flight.Scribe
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-scribe
synopsis: Hang gliding and paragliding competition scoring files.
description: Reading and writing competition scoring files.
category: Data
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - split
    - path
    - aeson
    - scientific
    - containers
    - unordered-containers
    - time
    - cassava
    - bytestring
    - directory
    - filepath
    - filemanip
    - mtl
    - yaml
    - vector
    - aeson-via-sci
    - flight-latlng
    - flight-zone
    - flight-route
    - flight-gap
    - flight-comp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
