flags: {}
packages:
- '.'
- location: ../aeson-via-sci
  extra-dep: true
- location: ../siggy-chardust
  extra-dep: true
- location: ../units
  extra-dep: true
- location: ../latlng
  extra-dep: true
- location: ../zone
  extra-dep: true
- location: ../task
  extra-dep: true
- location: ../route
  extra-dep: true
- location: ../gap
  extra-dep: true
- location: ../comp
  extra-dep: true
- location:
    git: https://github.com/danfran/hcoord.git
    commit: e308934570874a6ce7f7ebdbf51a3c34e4acd745
  extra-dep: true
- location:
    git: https://github.com/adamgundry/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps:
- hxt-xpath-9.1.2.2
resolver: nightly-2017-12-09
local-bin-path: ../__shake-build
