# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - containers
  - mtl
  - directory
  - filepath
  - flight-comp
  - flight-kml
  source-dirs: library
  exposed-modules:
  - Flight.TrackLog
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-track
synopsis: Hang gliding and paragliding competition track logs.
description: Reading track logs for each pilot in each task of a competition.
category: Data
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-track
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - containers
    - split
    - mtl
    - directory
    - filepath
    - flight-comp
    - flight-kml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
