library:
  source-dirs: library
  exposed-modules: Flight.TrackLog
tests: {}
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
category: Data
license-file: LICENSE.md
maintainer: phil.dejoux@blockscope.com
ghc-options:
- -Wall
dependencies:
- base >=4.9.1.0 && <5
- split
- path
- containers
- mtl
- directory
- filepath
- time
- bytestring
- utf8-string
- flight-comp
- flight-kml
- flight-igc
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
name: flight-track
version: 0.1.0
extra-source-files:
- package.dhall
- changelog.md
- README.md
synopsis: Hang gliding and paragliding competition track logs.
author: Phil de Joux
github: blockscope/flare-timing/track
tested-with: GHC == 8.2.2
license: MPL-2.0
description: Reading track logs for each pilot in each task of a competition.

