name: flight-track
version: '0.1.0'
synopsis: Hang gliding and paragliding competition track logs.
description: Reading track logs for each pilot in each task of a competition.
category: Data
github: BlockScope/haskell-flight-track
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options: -Wall

library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - containers
  - mtl
  - directory
  - filepath
  - time
  - flight-comp
  - flight-kml
  - flight-igc
  source-dirs: library
  exposed-modules:
  - Flight.TrackLog

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - containers
    - split
    - mtl
    - directory
    - filepath
    - time
    - flight-comp
    - flight-kml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
