name: tasty-compare
version: 0.1.0
synopsis: Tasty HUnit extensions for comparisons.
description: Adds assertCompare and operators for the same.
category: Test
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/tasty-compare
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- PackageImports
ghc-options:
- -Wall
dependencies:
- base >=4.9.1.0 && <5
- tasty
- tasty-hunit
- call-stack
library:
  exposed-modules: Test.Tasty.HUnit.Compare
  source-dirs: library
tests: {}

