# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options: -Wall
library:
  dependencies:
  - base
  - tasty
  - tasty-hunit
  - call-stack
  source-dirs: library
  exposed-modules:
  - Test.Tasty.HUnit.Compare
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: tasty-compare
synopsis: Tasty HUnit extensions for comparisons.
description: Adds assertCompare and operators for the same.
category: Test
license: BSD3
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/tasty-compare
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - tasty
    - tasty-hunit
    - call-stack
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
