name: tasty-compare
version: '0.1.0'
synopsis: Tasty HUnit extensions for comparisons.
description: Adds assertCompare and operators for the same.
category: Test
github: blockscope/flare-timing/tasty-compare
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options: -Wall

library:
  dependencies:
  - base
  - tasty
  - tasty-hunit
  - call-stack
  source-dirs: library
  exposed-modules:
  - Test.Tasty.HUnit.Compare

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - tasty
    - tasty-hunit
    - call-stack
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
