# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
executables:
  comp-serve:
    dependencies:
    - base
    - servant
    - servant-server
    - transformers
    - aeson
    - wai
    - wai-cors
    - warp
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - yaml
    - bytestring
    - flight-comp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: serve
extra-source-files:
- package.yaml
- changelog.md
- readme.md
ghc-options: -Wall
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: www
synopsis: A collection of apps and libraries for scoring hang gliding and paragliding competitions.
description: Scoring and viewing hang gliding and paragliding competitions.
category: Data, Parsing
license: BSD3
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - flight-comp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - test-suite-hlint
version: '0.1.0'
