# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - uom-plugin
  - bifunctors
  - aeson
  - scientific
  - aeson-via-sci
  - siggy-chardust
  - flight-units
  - flight-latlng
  source-dirs: library
  exposed-modules:
  - Flight.Zone
  - Flight.Zone.Raw
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-zone
synopsis: Control zones to fly.
description: Control zones for hang gliding and paragliding competitons.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - aeson-via-sci
    - siggy-chardust
    - flight-units
    - flight-latlng
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
