flags: {}
packages:
- '.'
- location: ../siggy-chardust
  extra-dep: true
- location: ../aeson-via-sci
  extra-dep: true
- location: ../aeson-via-uom
  extra-dep: true
- location: ../units
  extra-dep: true
- location: ../latlng
  extra-dep: true
- location:
    git: https://github.com/adamgundry/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps: []
resolver: nightly-2018-01-09
local-bin-path: ../__shake-build
