name: siggy-chardust
version: '0.1.0'
synopsis: Rounding keeping decimal places and significant digits.
description: Round to a certain number of decimal places or significant digits.
category: Data, Math
github: BlockScope/haskell-siggy-chardust
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options: -Wall

library:
  dependencies:
  - base >=4.5 && <5
  source-dirs: library
  exposed-modules:
  - Data.Number.RoundingFunctions

tests:
  hlint:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  digits:
    dependencies:
    - base
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Rounding.hs
    source-dirs:
    - library
    - test-suite-digits
