# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - numbers
  - scientific
  - aeson
  - cassava
  - bytestring
  - uom-plugin
  - formatting
  - text
  - siggy-chardust
  - flight-units
  source-dirs: library
  exposed-modules:
  - Flight.LatLng
  - Flight.LatLng.Raw
  - Flight.LatLng.Double
  - Flight.LatLng.Float
  - Flight.LatLng.Rational
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-latlng
synopsis: Latitude and longitude as used in hang gliding and paragliding competitions.
description: Latitude and longitude.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - numbers
    - scientific
    - aeson
    - cassava
    - uom-plugin
    - formatting
    - text
    - siggy-chardust
    - flight-units
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
