flags: {}
packages:
- '.'
- location: ../siggy-chardust
  extra-dep: true
- location: ../units
  extra-dep: true
- location:
    git: https://github.com/adamgundry/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps: []
resolver: lts-9.3
local-bin-path: ../__shake-build
