name: flight-comp
version: 0.1.0
synopsis: Hang gliding and paragliding competition scoring inputs.
description: Hang gliding and paragliding competitors and tasks.
category: Data
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/comp
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
dependencies:
- base >=4.9.1.0 && <5
- split
- path
- aeson
- scientific
- containers
- unordered-containers
- time
- cassava
- bytestring
- directory
- filepath
- filemanip
- lens
- mtl
- uom-plugin
- vector
- detour-via-sci
- flight-units
- flight-latlng
- flight-zone
- flight-route
- flight-gap
library:
  exposed-modules:
  - Flight.Comp
  - Flight.Track.Cross
  - Flight.Track.Tag
  - Flight.Track.Time
  - Flight.Track.Mask
  - Flight.Track.Land
  - Flight.Track.Point
  - Flight.Track.Speed
  - Flight.Track.Arrival
  - Flight.Track.Lead
  - Flight.Track.Distance
  source-dirs: library
tests:
  comp:
    main: TestCompMain.hs
    source-dirs:
    - library
    - test-suite-comp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck

