# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - aeson
  - scientific
  - containers
  - time
  - flight-latlng
  - flight-zone
  source-dirs: library
  exposed-modules:
  - Data.Flight.Comp
  - Data.Flight.PilotTrack
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-comp 
synopsis: Hang gliding and paragliding competition scoring inputs.
description: Hang gliding and paragliding competitors and tasks.
category: Data
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - aeson
    - scientific
    - containers
    - split
    - time
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
