# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - split
  - path
  - aeson
  - scientific
  - containers
  - unordered-containers
  - time
  - cassava
  - bytestring
  - directory
  - filepath
  - filemanip
  - lens
  - mtl
  - uom-plugin
  - vector
  - aeson-via-sci
  - flight-units
  - flight-latlng
  - flight-zone
  - flight-route
  - flight-gap
  source-dirs: library
  exposed-modules:
  - Flight.Comp
  - Flight.Track.Cross
  - Flight.Track.Tag
  - Flight.Track.Time
  - Flight.Track.Mask
  - Flight.Track.Land
  - Flight.Track.Point
  - Flight.Track.Speed
  - Flight.Track.Arrival
  - Flight.Track.Lead
  - Flight.Track.Distance
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-comp
synopsis: Hang gliding and paragliding competition scoring inputs.
description: Hang gliding and paragliding competitors and tasks.
category: Data
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - split
    - path
    - aeson
    - scientific
    - containers
    - unordered-containers
    - time
    - cassava
    - bytestring
    - directory
    - filepath
    - filemanip
    - lens
    - mtl
    - uom-plugin
    - vector
    - aeson-via-sci
    - flight-units
    - flight-latlng
    - flight-zone
    - flight-route
    - flight-gap
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
