name: flight-igc
version: '0.1.0'
synopsis: A parser for IGC files.
description: IGC is a waypoint file format from the International Gliding Commission of FAI. This haskell library can parse B records from these files.
category: Data, Parsing
github: blockscope/flare-timing/igc
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options: -Wall

library:
  dependencies:
  - base >=4.5 && <5
  - parsec
  source-dirs: library
  exposed-modules:
  - Flight.Igc

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - flight-igc 
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs: test-suite
