name: flight-igc
version: 1.0.0
synopsis: A parser for IGC files.
description: IGC is a waypoint file format from the International Gliding Commission
  of FAI. This haskell library can parse B records from these files.
category: data, parsing
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/igc
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
dependencies:
- base >=4.9.1.0 && <5
- parsec
- bytestring
- utf8-string
library:
  exposed-modules: Flight.Igc
  source-dirs: library
tests: {}

