name: flight-cmd
version: '0.1.0'
synopsis: Command line options.
description: Command line options such as file or directory, task or pilot.
category: Flight
github: blockscope/flare-timing/cmd
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options:
- -Wall

library:
  dependencies:
  - base >=4.5 && <5
  - directory
  - filepath
  - system-filepath
  - filemanip
  - raw-strings-qq
  - cmdargs
  - mtl
  - transformers
  - flight-span
  source-dirs: library
  exposed-modules:
  - Flight.Cmd.Options
  - Flight.Cmd.Paths

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    - flight-span
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
