# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - directory
  - filepath
  - system-filepath
  - filemanip
  - raw-strings-qq
  - cmdargs
  - mtl
  - transformers
  source-dirs: library
  exposed-modules:
  - Flight.Cmd.Options
  - Flight.Cmd.Paths
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-cmd
synopsis: Command line options.
description: Command line options such as file or directory, task or pilot.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/flare-timing
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - directory
    - filepath
    - system-filepath
    - filemanip
    - raw-strings-qq
    - cmdargs
    - mtl
    - transformers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
