# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - numbers
  - fgl
  - uom-plugin
  - bifunctors
  - aeson
  - scientific
  - mtl
  - hcoord
  - hcoord-utm
  - aeson-via-sci
  - siggy-chardust
  - flight-units
  - flight-latlng
  - flight-zone
  source-dirs: library
  exposed-modules:
  - Flight.Earth.Flat.Projected.Double
  - Flight.Earth.Flat.Projected.Rational
  - Flight.Earth.Flat.Separated
  - Flight.Earth.Flat
  - Flight.Earth.Sphere.Cylinder.Double
  - Flight.Earth.Sphere.Cylinder.Rational
  - Flight.Earth.Sphere.PointToPoint.Double
  - Flight.Earth.Sphere.PointToPoint.Rational
  - Flight.Earth.Sphere.Separated
  - Flight.Earth.Sphere
  - Flight.Earth.Ellipsoid.Cylinder.Double
  - Flight.Earth.Ellipsoid.Cylinder.Rational
  - Flight.Earth.Ellipsoid.PointToPoint.Double
  - Flight.Earth.Ellipsoid.PointToPoint.Rational
  - Flight.Earth.Ellipsoid.Separated
  - Flight.Earth.Ellipsoid
  - Flight.Earth.Geodesy
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-earth
synopsis: Distances on the WGS84 ellipsoid, the FAI sphere and the UTM projection.
description: Distances on the Earth for hang gliding and paragliding competitons.
category: Flight
license: BSD3
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/haskell-flight-task
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - numbers
    - fgl
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - mtl
    - hcoord
    - hcoord-utm
    - aeson-via-sci
    - siggy-chardust
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  earth:
    dependencies:
    - base
    - hlint
    - numbers
    - fgl
    - uom-plugin
    - bifunctors
    - aeson
    - scientific
    - mtl
    - hcoord
    - aeson-via-sci
    - siggy-chardust
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    - tasty-compare
    - flight-units
    - flight-latlng
    - flight-zone
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Earth.hs
    source-dirs:
    - library
    - test-suite-earth
version: '0.1.0'
