name: flight-earth
version: 0.1.0
synopsis: Distances on the WGS84 ellipsoid, the FAI sphere and the UTM projection.
description: Distances on the Earth for hang gliding and paragliding competitons.
category: Flight
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/earth
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
dependencies:
- base >=4.9.1.0 && <5
- numbers
- fgl
- uom-plugin
- bifunctors
- aeson
- scientific
- mtl
- hcoord
- hcoord-utm
- detour-via-sci
- siggy-chardust
- flight-units
- flight-latlng
- flight-zone
library:
  exposed-modules:
  - Flight.Earth.Flat.Projected.Double
  - Flight.Earth.Flat.Projected.Rational
  - Flight.Earth.Flat.Separated
  - Flight.Earth.Flat
  - Flight.Earth.Sphere.Cylinder.Double
  - Flight.Earth.Sphere.Cylinder.Rational
  - Flight.Earth.Sphere.PointToPoint.Double
  - Flight.Earth.Sphere.PointToPoint.Rational
  - Flight.Earth.Sphere.Separated
  - Flight.Earth.Sphere
  - Flight.Earth.Ellipsoid.Cylinder.Double
  - Flight.Earth.Ellipsoid.Cylinder.Rational
  - Flight.Earth.Ellipsoid.PointToPoint.Double
  - Flight.Earth.Ellipsoid.PointToPoint.Rational
  - Flight.Earth.Ellipsoid.Separated
  - Flight.Earth.Ellipsoid
  - Flight.Earth.Geodesy
  source-dirs: library
tests:
  earth:
    main: Earth.hs
    source-dirs:
    - library
    - test-suite-earth
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    - tasty-compare

