name: flight-span
version: '0.1.0'
synopsis: How to measure a distance that spans two points.
description: How to measure a distance that spans tow points.
category: Data
github: BlockScope/haskell-flight-mask
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options: -Wall

library:
  dependencies:
  - base >=4.5 && <5
  - cmdargs
  source-dirs: library
  exposed-modules:
  - Flight.Span.Math

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - cmdargs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
