# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options: -Wall
library:
  dependencies:
  - base >=4.5 && <5
  - cmdargs
  source-dirs: library
  exposed-modules:
  - Flight.Span.Math
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
name: flight-span
synopsis: How to measure a distance that spans two points.
description: How to measure a distance that spans tow points.
category: Data
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/haskell-flight-mask
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - cmdargs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
