library:
  source-dirs: library
  exposed-modules:
  - Flight.Route
  - Flight.TaskTrack.Double
  - Flight.TaskTrack.Rational
tests: {}
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
category: Flight
license-file: LICENSE.md
maintainer: phil.dejoux@blockscope.com
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
dependencies:
- base >=4.9.1.0 && <5
- numbers
- uom-plugin
- bifunctors
- aeson
- scientific
- hcoord-utm
- detour-via-sci
- siggy-chardust
- flight-units
- flight-latlng
- flight-zone
- flight-earth
- flight-task
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
name: flight-route
version: 0.1.0
extra-source-files:
- package.dhall
- changelog.md
- README.md
synopsis: Control zones to fly.
author: Phil de Joux
github: blockscope/flare-timing/route
tested-with: GHC == 8.2.2
license: MPL-2.0
description: Control zones for hang gliding and paragliding competitons.

