# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - numbers
  - bifunctors
  - text
  - formatting
  - uom-plugin
  - siggy-chardust
  source-dirs: library
  exposed-modules:
  - Flight.Units
  - Flight.Units.Angle
  - Flight.Units.DegMinSec
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-units
synopsis: Units used in hang gliding and paragliding competitions.
description: Unit definitions such as m, km, rad and deg.
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/haskell-flight-task
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - numbers
    - bifunctors
    - text
    - formatting
    - uom-plugin
    - siggy-chardust
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
version: '0.1.0'
