library:
  source-dirs: library
  exposed-modules:
  - Flight.Mask
  - Flight.Comp.Distance
  - Flight.Span.Double
  - Flight.Span.Rational
tests: {}
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
category: Data
license-file: LICENSE.md
maintainer: phil.dejoux@blockscope.com
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
dependencies:
- base >=4.9.1.0 && <5
- split
- path
- containers
- mtl
- directory
- filepath
- time
- lens
- bytestring
- yaml
- uom-plugin
- fgl
- cmdargs
- numbers
- detour-via-sci
- flight-span
- flight-units
- flight-comp
- flight-kml
- flight-latlng
- flight-zone
- flight-route
- flight-track
- flight-earth
- flight-task
- flight-gap
- flight-scribe
- siggy-chardust
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
name: flight-mask
version: 0.1.0
extra-source-files:
- package.dhall
- changelog.md
- README.md
synopsis: Track logs masked by competition task zones.
author: Phil de Joux
github: blockscope/flare-timing/mask
tested-with: GHC == 8.2.2
license: MPL-2.0
description: Masking tracks with zones, work out; did the pilot launch, did they make
  goal and how long did that take? What was distance to goal?

