name: flight-gap
version: '0.1.0'
synopsis: GAP Scoring.
description: GAP scoring for hang gliding and paragliding competitons.
category: Flight
github: BlockScope/haskell-flight-gap
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: Phil de Joux 2017-2018
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
extra-source-files:
- package.yaml
- changelog.md
- README.md

ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin

library:
  dependencies:
  - base >=4.5 && <5
  - containers
  - vector
  - statistics
  - aeson
  - newtype
  - scientific
  - uom-plugin
  - template-haskell
  - aeson-via-sci
  - aeson-via-uom
  - siggy-chardust
  - flight-units
  source-dirs: library
  exposed-modules:
  - Flight.Score

tests:
  hlint:
    dependencies:
    - base
    - hlint
    - containers
    - vector
    - statistics
    - aeson
    - newtype
    - scientific
    - uom-plugin
    - aeson-via-sci
    - aeson-via-uom
    - siggy-chardust
    - flight-units
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  score:
    dependencies:
    - base
    - containers
    - vector
    - statistics
    - aeson
    - newtype
    - scientific
    - uom-plugin
    - aeson-via-sci
    - aeson-via-uom
    - siggy-chardust
    - flight-units
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Score.hs
    source-dirs:
    - library
    - test-suite-score
