# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- changelog.md
- README.md
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
library:
  dependencies:
  - base >=4.5 && <5
  - containers
  - vector
  - statistics
  - aeson
  - newtype
  - scientific
  - uom-plugin
  - template-haskell
  - aeson-via-sci
  - aeson-via-uom
  - siggy-chardust
  - flight-units
  source-dirs: library
  exposed-modules:
  - Flight.Score
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: flight-gap 
synopsis: GAP Scoring.
description: GAP scoring for hang gliding and paragliding competitons.
category: Flight
license: BSD3
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: BlockScope/haskell-flight-gap
tests:
  hlint:
    dependencies:
    - base
    - hlint
    - containers
    - vector
    - statistics
    - aeson
    - newtype
    - scientific
    - uom-plugin
    - aeson-via-sci
    - aeson-via-uom
    - siggy-chardust
    - flight-units
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: HLint.hs
    source-dirs:
    - library
    - test-suite-hlint
  score:
    dependencies:
    - base
    - containers
    - vector
    - statistics
    - aeson
    - newtype
    - scientific
    - uom-plugin
    - aeson-via-sci
    - aeson-via-uom
    - siggy-chardust
    - flight-units
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    main: Score.hs
    source-dirs:
    - library
    - test-suite-score
version: '0.1.0'
