name: flight-gap
version: 0.1.0
synopsis: GAP Scoring.
description: GAP scoring for hang gliding and paragliding competitons.
category: Flight
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE.md
tested-with: GHC == 8.2.2
github: blockscope/flare-timing/gap
extra-source-files:
- package.dhall
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
- -fplugin Data.UnitsOfMeasure.Plugin
- -fno-warn-partial-type-signatures
dependencies:
- base >=4.9.1.0 && <5
- containers
- vector
- statistics
- aeson
- newtype
- scientific
- uom-plugin
- template-haskell
- detour-via-sci
- detour-via-uom
- siggy-chardust
- flight-units
library:
  exposed-modules: Flight.Score
  source-dirs: library
tests:
  score:
    main: Score.hs
    source-dirs:
    - library
    - test-suite-score
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin Data.UnitsOfMeasure.Plugin
    dependencies:
    - base
    - containers
    - vector
    - statistics
    - aeson
    - newtype
    - scientific
    - uom-plugin
    - detour-via-sci
    - detour-via-uom
    - siggy-chardust
    - flight-units
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - smallcheck

